# Generated by Django 4.2.2 on 2023-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('group', models.CharField(max_length=300)),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drink_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Info_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('q_name', models.CharField(max_length=1500)),
                ('address', models.CharField(max_length=10000)),
                ('user_id', models.IntegerField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('buy_unit', models.CharField(max_length=1500)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('value', models.IntegerField()),
                ('buy_unit', models.CharField(max_length=100)),
                ('change_unit', models.CharField(max_length=100)),
                ('change_value', models.CharField(max_length=100)),
                ('main_drink', models.CharField(max_length=100)),
                ('main_drink_id', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
